### ISSUE TITLE
Embed Video: Additional tags

### ISSUE THREAD

**Issue by StevenLangbroek** [krea/EE_Field_Pack#10]
Hey guys,

I'm using Content Elements and Embed Video to create a mixed slideshow, but I'm running into a limitation. I have no way to get a thumbnail for a YouTube or Vimeo video. Is this something you could add? For YouTube just making the Video ID available would be enough for me. Would love to hear your input.

Thanks,
- Steven

**Comment by MarioPalkaKrea** [comment]
Hello Steven,

of course there a space to improve our fieldtype, but I would need specify your request by example of usage in template and in Control panel. Could you please briefly describe, how it should work to cover your needs?

Best regards,

Mario Palka

**Comment by StevenLangbroek** [comment]
Hey Mario,

The back-end is absolutely fine, but I think templating should work something along these lines:

```
{my_content_elements_field}
    {embed_video}
        {youtube}
            <a href="http://www.youtube.com/watch?v={video_id}">
                <img src="https://img.youtube.com/vi/{video_id}/default.jpg" alt="{video_label}">
            </a>
        {/youtube}
        {vimeo}
            <a href="http://vimeo.com/{video_id}">
                <img src="https://vimeo.com/some-thumbnail-path/{video_id}.jpg" alt="{video_label}">
            </a>
        {/vimeo}
    {/embed_video}
{/my_content_elements_field}
```

How does that look/sound to you?

Cheers!
- Steven

**Comment by MarioPalkaKrea** [comment]
Hello Steven,

I will consider it, but I think I can pass to the output of field type video_id, so you can create link as you need. Is this solution good enough for you?

Mario

**Comment by StevenLangbroek** [comment]
Yep, that'd be awesome (it's what I need most right now). Thanks alot Mario!

**Comment by MarioPalkaKrea** [comment]
Fixed. You can now use template tag {video_id}, supports YouTube.

**Comment by StevenLangbroek** [comment]
Thanks alot guys! Do you have a Paypal e-mailaddress so I can sponsor you a case of beer? :)

**Comment by peterfelix** [comment]
Hello Steven, 

a cool post on twitter will do just fine and we can have a beer once in Netherlands or on a conference... :)

Thanks,
Peter
