### ISSUE TITLE
PHP Error when using Picture Content Elements block

### ISSUE THREAD

**Issue by nathanpitman** [krea/EE_Field_Pack#14]
I'm getting a PHP Error notice as follows where I'm using the Picture content block:

```
Severity: Notice

Message: Undefined index: file_dimensions

Filename: picture/ft.picture.php
```

My page template logic is uncomplicated and so far as I can tell it seems to stem from the fact that I have no rows in the exp_file_dimensions table, would I be right in thinking that line 426 in ft.picture.php:

```
$file_dimensions = self::$cache["file_dimensions"];
```

Is at fault and that this field type assumes that files uploaded to EE all have entries in the exp_file_dimensions table...

:?

**Comment by nathanpitman** [comment]
Hi there, any further thoughts on this? I'm quite happy to fix if you agree with my assumption?

**Comment by mvarga** [comment]
Thanks, i commit your fixes.

**Comment by nathanpitman** [comment]
Cheers, you might want to test yourself, I'm only using the field in a scenario where there are no rows in exp_file_dimensions because I'm only storing the original, not creating sized versions on upload.
